name: Build docker image

permissions:
    contents: read

on:
    push:
        branches:
          - "*"
        tags-ignore:
          - "*"

jobs:
    build-image:
        name: Build the image
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                platform: ["linux/arm/v6", "linux/arm/v7", "linux/arm64/v8", "linux/386", "linux/ppc64le", "linux/amd64"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build docker image
              run: make docker-build
              env:
                DOCKER_BUILDKIT: 1
                PLATFORM: ${{ matrix.platform }}

            - name: Test image
              if: ${{ matrix.platform == 'linux/amd64' }}
              run: make docker-test
